# Generated by Django 3.2.6 on 2022-11-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
